title: "Genome Assembly workshop"
baseurl: /workshop-genome_assembly

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: index
  - title: Uppmax Login
    url: uppmax_login
  - title: Schedule
    url: schedule
  - title: Travel info
    url: travel
  - title: Workshop Material
    submenus:
      - title: Exercise
