title: "Genome Assembly workshop"
baseurl: /workshop-genome_assembly

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: 2017-11-15/index
  - title: Schedule
    url: 2017-11-15/schedule
  - title: Pre-course material
    url: 2017-11-15/precourse
  - title: Travel info
    url: 2017-11-15/travel
  - title: Labs
    submenus:
      - title: Data Quality Assessment
        url: 2017-11-15/exercises/Exercise_Data_Quality_Assessment
      - title: K-mer and Contamination Analysis
        url: 2017-11-15/exercises/Exercise_K-mer_and_Contamination_Analysis
      - title: Illumina Assembly
        url: 2017-11-15/exercises/Exercise_Illumina_Assembly
      - title: Long read Assembly
        url: 2017-11-15/exercises/Exercise_Long_Read_Assembly
      - title: Assembly Validation
        url: 2017-11-15/exercises/Exercise_Assembly_Validation
      - title: Group Exercise
        url: 2017-11-15/exercises/Exercise_Diatom_assembly_project

