title: "Genome Assembly workshop"
baseurl: /workshop-genome_assembly

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: index
  - title: Information
    url: information
  - title: Schedule
    url: schedule
  - title: Travel info
    url: travel
  - title: Labs
    submenus:
      - title: Data Quality Assessment
        url: exercises/Exercise_Data_Quality_Assessment
      - title: K-mer and Contamination Analysis
        url: exercises/Exercise_K-mer_and_Contamination_Analysis
      - title: Illumina Assembly
        url: exercises/Exercise_Illumina_Assembly
      - title: Long read Assembly
        url: exercises/Exercise_Long_Read_Assembly
      - title: Assembly Validation
        url: exercises/Exercise_Assembly_Validation
      - title: Group Exercise
        url: exercises/Exercise_Diatom_assembly_project
  - title: Reference
    submenus:
      - title: Sequencing Technologies
        url: reference/sequencing_technologies.md
      - title: File formats
        url: reference/file_formats.md

